export { default as Login } from './Login/Login'
export { default as Home } from './Home/Home'
export { default as Community } from './Community/Community'
export { default as Profile } from './Profile/Profile'
export { default as SignUp } from './SignUp/sign-up'